const { DataTypes } = require("sequelize");
const sequelize = require("../config/database");

const AdoptionApp = sequelize.define(
  "adoption_app",
  {
    user_id: { type: DataTypes.INTEGER, allowNull: false },
    reptileDescription: { type: DataTypes.STRING, allowNull: false },
    primaryName: { type: DataTypes.STRING, allowNull: false },
    primaryPhone: { type: DataTypes.STRING, allowNull: false },
    primaryEmail: { type: DataTypes.STRING, allowNull: false },
    primaryEmployment: { type: DataTypes.STRING },
    primaryWorkPhone: { type: DataTypes.STRING },
    primaryOccupation: { type: DataTypes.STRING },
    primaryTimeEmployer: { type: DataTypes.STRING },
    coName: { type: DataTypes.STRING },
    coPhone: { type: DataTypes.STRING },
    coEmail: { type: DataTypes.STRING },
    coEmployment: { type: DataTypes.STRING },
    previousExperience: { type: DataTypes.STRING },
    primaryEnclosureLocation: { type: DataTypes.STRING },
    enclosureDescription: { type: DataTypes.TEXT },
    additionalComments: { type: DataTypes.TEXT },
    address: { type: DataTypes.STRING },
    city: { type: DataTypes.STRING },
    stateZip: { type: DataTypes.STRING },
    rentOrOwn: { type: DataTypes.STRING },
    landlordName: { type: DataTypes.STRING },
    landlordPhone: { type: DataTypes.STRING },
    othersResiding: { type: DataTypes.STRING },
    residingDetails: { type: DataTypes.STRING },
    childrenLiving: { type: DataTypes.STRING },
    numberChildren: { type: DataTypes.INTEGER },
    agesChildren: { type: DataTypes.STRING },
    childrenExperience: { type: DataTypes.STRING },
    reference1Name: { type: DataTypes.STRING },
    reference1Phone: { type: DataTypes.STRING },
    reference2Name: { type: DataTypes.STRING },
    reference2Phone: { type: DataTypes.STRING },
    certifyTrue: { type: DataTypes.BOOLEAN },
    certifyFinancial: { type: DataTypes.BOOLEAN },
    certifyAccept: { type: DataTypes.BOOLEAN },
    signature: { type: DataTypes.STRING },
    date: { type: DataTypes.DATEONLY },
    status: {
      type: DataTypes.STRING,
      allowNull: false,
      defaultValue: "pending",
      validate: { isIn: [["approved", "pending", "rejected"]] },
    },
  },
  {
    tableName: "adoption_apps",
    timestamps: true,
  },
);

module.exports = AdoptionApp;